### ISSUE TITLE
Use a lib for handling the CLI implementation for python

### ISSUE THREAD

**Issue by thoroc** [aprxi/faster-data-generation#2]
I have noticed that you are using clap for the Rust v2 but have not used anything for the Python v2. Maybe do a python v3 that uses click? https://click.palletsprojects.com/en/8.1.x/

**Comment by aprxi** [comment]
Thanks for suggestion. Yes am aware of click. However, we just intent to keep a small demo-scope, and as such expect the build-in argparse library is already quite sufficient.
